///////////////////////////////////////////////////////////////////////////
// Description: Business Object Base class for the 'Address'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Reflection;
using System.Collections;
using System.EnterpriseServices;

using FindMyFamilies.Data;
using FindMyFamilies.Util;
using FindMyFamilies.Exceptions;
using FindMyFamilies.Transactions;
using FindMyFamilies.DataAccess;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.BusinessObject {

	/// <summary>
	/// Purpose: Business Object base class for Address
	/// </summary>
	public class AddressBOBase : BusinessObjectBase {
		// Constant Declarations
		private static readonly object logCategory = MethodBase.GetCurrentMethod().DeclaringType;
		private static AddressDAO m_AddressDAO;

		// Property Declarations
		public static AddressDAO AddressDAO {
			get {
				if (m_AddressDAO == null) {
					AddressBOBase addressBO = new AddressBOBase();
					lock(addressBO) {
						m_AddressDAO = new AddressDAO();
					}
				}
				return m_AddressDAO;
			}
		}

		public virtual AddressDO CreateAddress(AddressDO addressDO) {
			return AddressDAO.CreateAddress(addressDO);
		}

		public virtual AddressDO ReadAddress(AddressDO addressDO) {
			return AddressDAO.ReadAddress(addressDO);
		}

		public virtual ICollection ReadAddresssAll(DataTransferObject dataTransferObject) {
			return AddressDAO.ReadAddresssAll(dataTransferObject);
		}

		public virtual void UpdateAddress(AddressDO addressDO) {
			AddressDAO.UpdateAddress(addressDO);
		}

		public virtual void DeleteAddress(AddressDO addressDO) {
			AddressDAO.DeleteAddress(addressDO);
		}

		public virtual ICollection ReadAddresssByPage(AddressDO addressDO) {
			return AddressDAO.ReadAddresssByPage(addressDO);
		}

	}
}
