///////////////////////////////////////////////////////////////////////////
// Description: Business Object Base class for the 'App_Settings'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Reflection;
using System.Collections;
using System.EnterpriseServices;

using FindMyFamilies.Data;
using FindMyFamilies.Util;
using FindMyFamilies.Exceptions;
using FindMyFamilies.Transactions;
using FindMyFamilies.DataAccess;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.BusinessObject {

	/// <summary>
	/// Purpose: Business Object base class for AppSettings
	/// </summary>
	public class AppSettingsBOBase : BusinessObjectBase {
		// Constant Declarations
		private static readonly object logCategory = MethodBase.GetCurrentMethod().DeclaringType;
		private static AppSettingsDAO m_AppSettingsDAO;

		// Property Declarations
		public static AppSettingsDAO AppSettingsDAO {
			get {
				if (m_AppSettingsDAO == null) {
					AppSettingsBOBase appSettingsBO = new AppSettingsBOBase();
					lock(appSettingsBO) {
						m_AppSettingsDAO = new AppSettingsDAO();
					}
				}
				return m_AppSettingsDAO;
			}
		}

		public virtual AppSettingsDO CreateAppSettings(AppSettingsDO appSettingsDO) {
			return AppSettingsDAO.CreateAppSettings(appSettingsDO);
		}

		public virtual AppSettingsDO ReadAppSettings(AppSettingsDO appSettingsDO) {
			return AppSettingsDAO.ReadAppSettings(appSettingsDO);
		}

		public virtual ICollection ReadAppSettingssAll(DataTransferObject dataTransferObject) {
			return AppSettingsDAO.ReadAppSettingssAll(dataTransferObject);
		}

		public virtual ICollection ReadAppSettingssAllList(DataTransferObject dataTransferObject) {
			return AppSettingsDAO.ReadAppSettingssAllList(dataTransferObject);
		}

		public virtual void UpdateAppSettings(AppSettingsDO appSettingsDO) {
			AppSettingsDAO.UpdateAppSettings(appSettingsDO);
		}

		public virtual void DeleteAppSettings(AppSettingsDO appSettingsDO) {
			AppSettingsDAO.DeleteAppSettings(appSettingsDO);
		}

		public virtual ICollection ReadAppSettingssByPage(AppSettingsDO appSettingsDO) {
			return AppSettingsDAO.ReadAppSettingssByPage(appSettingsDO);
		}

	}
}
