///////////////////////////////////////////////////////////////////////////
// Description: Business Object Base class for the 'Find_Person_Options'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Reflection;
using System.Collections;
using System.EnterpriseServices;

using FindMyFamilies.Data;
using FindMyFamilies.Util;
using FindMyFamilies.Exceptions;
using FindMyFamilies.Transactions;
using FindMyFamilies.DataAccess;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.BusinessObject {

	/// <summary>
	/// Purpose: Business Object base class for FindPersonOptions
	/// </summary>
	public class FindPersonOptionsBOBase : BusinessObjectBase {
		// Constant Declarations
		private static readonly object logCategory = MethodBase.GetCurrentMethod().DeclaringType;
		private static FindPersonOptionsDAO m_FindPersonOptionsDAO;

		// Property Declarations
		public static FindPersonOptionsDAO FindPersonOptionsDAO {
			get {
				if (m_FindPersonOptionsDAO == null) {
					FindPersonOptionsBOBase findPersonOptionsBO = new FindPersonOptionsBOBase();
					lock(findPersonOptionsBO) {
						m_FindPersonOptionsDAO = new FindPersonOptionsDAO();
					}
				}
				return m_FindPersonOptionsDAO;
			}
		}

		public virtual FindPersonOptionsDO CreateFindPersonOptions(FindPersonOptionsDO findPersonOptionsDO) {
			return FindPersonOptionsDAO.CreateFindPersonOptions(findPersonOptionsDO);
		}

		public virtual FindPersonOptionsDO ReadFindPersonOptions(FindPersonOptionsDO findPersonOptionsDO) {
			return FindPersonOptionsDAO.ReadFindPersonOptions(findPersonOptionsDO);
		}

		public virtual ICollection ReadFindPersonOptionssAll(DataTransferObject dataTransferObject) {
			return FindPersonOptionsDAO.ReadFindPersonOptionssAll(dataTransferObject);
		}

		public virtual void UpdateFindPersonOptions(FindPersonOptionsDO findPersonOptionsDO) {
			FindPersonOptionsDAO.UpdateFindPersonOptions(findPersonOptionsDO);
		}

		public virtual void DeleteFindPersonOptions(FindPersonOptionsDO findPersonOptionsDO) {
			FindPersonOptionsDAO.DeleteFindPersonOptions(findPersonOptionsDO);
		}

		public virtual ICollection ReadFindPersonOptionssByPage(FindPersonOptionsDO findPersonOptionsDO) {
			return FindPersonOptionsDAO.ReadFindPersonOptionssByPage(findPersonOptionsDO);
		}

	}
}
