///////////////////////////////////////////////////////////////////////////
// Description: Business Object Base class for the 'Member'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Reflection;
using System.Collections;
using System.EnterpriseServices;

using FindMyFamilies.Data;
using FindMyFamilies.Util;
using FindMyFamilies.Exceptions;
using FindMyFamilies.Transactions;
using FindMyFamilies.DataAccess;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.BusinessObject {

	/// <summary>
	/// Purpose: Business Object base class for Member
	/// </summary>
	public class MemberBOBase : BusinessObjectBase {
		// Constant Declarations
		private static readonly object logCategory = MethodBase.GetCurrentMethod().DeclaringType;
		private static MemberDAO m_MemberDAO;

		// Property Declarations
		public static MemberDAO MemberDAO {
			get {
				if (m_MemberDAO == null) {
					MemberBOBase memberBO = new MemberBOBase();
					lock(memberBO) {
						m_MemberDAO = new MemberDAO();
					}
				}
				return m_MemberDAO;
			}
		}

		public virtual MemberDO CreateMember(MemberDO memberDO) {
			return MemberDAO.CreateMember(memberDO);
		}

		public virtual MemberDO ReadMember(MemberDO memberDO) {
			return MemberDAO.ReadMember(memberDO);
		}

		public virtual ICollection ReadMembersAll(DataTransferObject dataTransferObject) {
			return MemberDAO.ReadMembersAll(dataTransferObject);
		}

		public virtual void UpdateMember(MemberDO memberDO) {
			MemberDAO.UpdateMember(memberDO);
		}

		public virtual void DeleteMember(MemberDO memberDO) {
			MemberDAO.DeleteMember(memberDO);
		}

		public virtual ICollection ReadMembersByPage(MemberDO memberDO) {
			return MemberDAO.ReadMembersByPage(memberDO);
		}

	}
}
