///////////////////////////////////////////////////////////////////////////
// Description: Business Object Base class for the 'Report'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Reflection;
using System.Collections;
using System.EnterpriseServices;

using FindMyFamilies.Data;
using FindMyFamilies.Util;
using FindMyFamilies.Exceptions;
using FindMyFamilies.Transactions;
using FindMyFamilies.DataAccess;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.BusinessObject {

	/// <summary>
	/// Purpose: Business Object base class for Report
	/// </summary>
	public class ReportBOBase : BusinessObjectBase {
		// Constant Declarations
		private static readonly object logCategory = MethodBase.GetCurrentMethod().DeclaringType;
		private static ReportDAO m_ReportDAO;

		// Property Declarations
		public static ReportDAO ReportDAO {
			get {
				if (m_ReportDAO == null) {
					ReportBOBase reportBO = new ReportBOBase();
					lock(reportBO) {
						m_ReportDAO = new ReportDAO();
					}
				}
				return m_ReportDAO;
			}
		}

		public virtual ReportDO CreateReport(ReportDO reportDO) {
			return ReportDAO.CreateReport(reportDO);
		}

		public virtual ReportDO ReadReport(ReportDO reportDO) {
			return ReportDAO.ReadReport(reportDO);
		}

		public virtual ICollection ReadReportsAll(DataTransferObject dataTransferObject) {
			return ReportDAO.ReadReportsAll(dataTransferObject);
		}

		public virtual void UpdateReport(ReportDO reportDO) {
			ReportDAO.UpdateReport(reportDO);
		}

		public virtual void DeleteReport(ReportDO reportDO) {
			ReportDAO.DeleteReport(reportDO);
		}

		public virtual ICollection ReadReportsByPage(ReportDO reportDO) {
			return ReportDAO.ReadReportsByPage(reportDO);
		}

	}
}
