///////////////////////////////////////////////////////////////////////////
// Description: Constants class
// generated by Generator v1.0.1190.16770 Final on: Saturday, April 05, 2003, 9:19:16 AM
///////////////////////////////////////////////////////////////////////////

using FindMyFamilies.DataAccess;

namespace  FindMyFamilies.DataAccess {
    /// <summary>
    ///     Purpose: Constants class
    /// </summary>
    public class DBConstants : DBConstantsBase {
        public const string ACTIVITY_LOG_READ_BY_PROJECT_TYPE = "sf_ActivityLog_ReadByProjectType";
        public const string ADDRESS_READ_BY_USER = "sf_Address_ReadByUser";
        public const string IMAGE_READ_BY_MAIN_HOME = "sf_Image_ReadByMainHome";
        public const string IMAGE_READ_BY_PROJECT = "sf_Image_ReadByProject";
        public const string IMAGE_DELETE_BY_PROJECT = "sf_Image_DeleteByProject";

        public const string PROJECT_READ_VIEW = "sf_Project_ReadView";
        public const string PROJECT_READ_MY_PROJECTS = "sf_Project_ReadByMyProjects";
        public const string PROJECT_READ_BY_REQUEST = "sf_Project_ReadByRequest";
        public const string PROJECT_READ_BY_STATUS = "sf_Project_ReadByStatus";
        public const string PROJECT_READ_BY_ACTIVE = "sf_Project_ReadByActive";

        public const string ROLE_READ_SYSTEM_ROLES = "sf_Role_ReadSystemRoles";
        public const string ROLE_READ_ROLES_BY_TYPE = "sf_Role_ReadByType";

        public const string ORGANIZATION_READ_LIST = "sf_Organization_ReadList";
        public const string ORGANIZATION_VERIFY_DELETE = "sf_Organization_VerifyDelete";

        public const string USER_PROJECT_READ_BY_PROJECT = "sf_UserProject_ReadByProject";
        public const string USER_PROJECT_DELETE_BY_PROJECT = "sf_UserProject_DeleteByProject";
        public const string USER_PROJECT_DELETE_BY_USER = "sf_UserProject_DeleteByUser";
        public const string USER_PROJECT_DELETE_BY_PROJECT_USER = "sf_UserProject_DeleteByProjectUser";
        public const string USER_PROJECT_DELETE_BY_PROJECT_ROLE = "sf_UserProject_DeleteByProjectRole";

        public const string USER_ROLE_DELETE_BY_USER = "sf_UserRole_DeleteByUser";
        public const string USER_ROLE_READ_BY_ROLE = "sf_UserRole_ReadByRole";
        public const string USER_ROLE_READ_LOGIN = "sf_UserRole_Read_Login";

        public const string USER_ROLE_READ_BY_AVAILABLE = "sf_UserRole_ReadByAvailable";
        public const string USER_ROLE_READ_BY_USER_AVAILABLE = "sf_UserRole_ReadByUserAvailable";
        public const string USER_ROLE_READ_BY_USER = "sf_UserRole_ReadByUser";

        public const string USER_READ_BY_USERNAME = "sf_User_ReadByUsername";
        public const string USER_READ_BY_NAME = "sf_User_ReadByName";
        public const string USER_READ_BY_ROLE = "sf_User_ReadByRole";
        public const string USER_READ_ONE_BY_ROLE = "sf_User_ReadOneByRole";
        public const string USER_READ_ONE_BY_EMAIL = "sf_User_ReadByEmail";
        public const string USER_VERIFY_DELETE = "sf_User_VerifyDelete";
        public const string USER_READ_ALL_BY_ROLE = "sf_User_ReadAllByRole";
        public const string USER_READ_BY_FIRSTNAME = "sf_User_ReadByFirstname";

        public const string CALENDAR_EVENT_READ_BY_MONTHLY = "sf_CalendarEvent_ReadByMonthly";

        public const string SESSION_DELETE_ALL = "sf_Session_DeleteAll";
        public const string SESSION_DELETE_EXPIRED_SESSIONS = "sf_Session_DeleteExpiredSessions";
        public const string SESSION_READ_GUID = "sf_Session_ReadGUID";
        public const string SESSION_READ_VALUE = "sf_Session_ReadValue";
        public const string SESSION_READ_VALUES = "sf_Session_ReadValues";
        public const string SESSION_UPDATE_VALUE = "sf_Session_UpdateValue";

        public const string DONATION_READ_BY_USER = "sf_Donation_ReadByUser";
        public const string DONATION_READ_BY_PROJECT = "sf_Donation_ReadByProject";

        public const string REPORT_ROLE_READ_BY_REPORT_AVAILABLE = "sf_ReportRole_ReadByReportAvailable";
        public const string REPORT_ROLE_READ_BY_REPORT = "sf_ReportRole_ReadByReport";
        public const string REPORT_ROLE_DELETE_BY_REPORT = "sf_ReportRole_DeleteByReport";
        public const string REPORT_READ_BY_PAGE = "sf_Report_ReadByPage";
    }
}