///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the 'Next_ID'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using System.Text;
using System.EnterpriseServices;
using System.Reflection;


using FindMyFamilies.Data;
using FindMyFamilies.Util;
using FindMyFamilies.Exceptions;
using FindMyFamilies.DataAccess;

namespace FindMyFamilies.DataAccess {
	/// <summary>
	/// Purpose: Data Access class for the 'Next_ID'.
	/// </summary>
	public class NextIDDAO : NextIDDAOBase {
		private static readonly object logCategory = System.Reflection.MethodBase.GetCurrentMethod().DeclaringType;
		// Stored Procedure Name Constants

		// Field Name Constants

		/// <summary>
		/// Purpose: Base Class constructor.
		/// </summary>
		public NextIDDAO() : base() {
		}

		/// <summary>
		/// Purpose: Creates a new record in Next_ID table and returns the generated primary key by reference.
		/// </summary>
		/// <param name = "nextIDDO">NextIDDO nextIDDO</param>
		public override NextIDDO CreateNextID(NextIDDO nextIDDO) {
			return base.CreateNextID(nextIDDO);
		}

		/// <summary>
		/// Purpose: Update a record in Next_ID.
		/// </summary>
		/// <param name = "nextIDDO">NextIDDO nextIDDO</param>
		public override void UpdateNextID(NextIDDO nextIDDO) {
			base.UpdateNextID(nextIDDO);
		}

		/// <summary>
		/// Purpose: Delete a record in Next_ID.
		/// </summary>
		/// <param name = "nextIDDO">NextIDDO nextID</param>
		public override void DeleteNextID(NextIDDO nextIDDO) {
			base.DeleteNextID(nextIDDO);
		}

		/// <summary>
		/// Purpose: RetrieveFamilySearchData a record in Next_ID table by primary key.
		/// </summary>
		/// <param name = "nextIDDO">NextIDDO nextIDDO.</param>
		public override NextIDDO ReadNextID(NextIDDO nextIDDO) {
			return base.ReadNextID(nextIDDO);
		}

		/// <summary>
		/// Purpose: Retrieves all records in Next_ID table.
		/// </summary>
		/// <param name = "dataTransferObject">DataTransferObject dataTransferObject.</param>
		public override ICollection ReadNextIDsAll(DataTransferObject dataTransferObject) {
			return base.ReadNextIDsAll(dataTransferObject);
		}

		/// <summary>
		/// Purpose: Reads a page of records from table Next_ID by search criteria.
		/// </summary>
		/// <returns>Returns a collection of NextIDs</returns>
		public virtual ICollection ReadNextIDsByPage(NextIDDO nextIDDO) {
			IList nextIDs = new ArrayList();
			IDataReader reader = null;
			try {
				IDataCommand command = dataSource.GetCommand(PagingDO.READ_BY_PAGE);
				command.SetParameter(PagingDO.PAGING_TABLE_NAME, TABLE_NAME);
				command.SetParameter(PagingDO.PAGING_PRIMARY_KEY, NextIDDAO.TABLE_ID);
				command.SetParameter(PagingDO.PAGING_FIELDS, "*");
				command.SetParameter(PagingDO.PAGING_ORDER, NextIDDAO.TABLE_ID);
				command.SetParameter(PagingDO.PAGING_PAGE_SIZE, nextIDDO.Paging.PageSize);
				command.SetParameter(PagingDO.PAGING_PAGE_INDEX, nextIDDO.Paging.PageIndex);
				command.SetParameter(PagingDO.PAGING_FILTER, NextIDDAO.TABLE_ID + " > 1");
				command.SetParameter(LANGUAGE, nextIDDO.Language);
				reader = command.ExecuteReader();
		
				// populate the detail object from the SQL Server Data Reader
				while (reader.Read()) {
					nextIDs.Add(this.MapToDataTransferObject(reader));
				}
				if (reader.NextResult()) {
					reader.Read();
					if (nextIDs.Count < 1) {
						nextIDs.Add(new NextIDDO());
					}
					((NextIDDO)nextIDs[0]).Paging.TotalRecords = reader.GetInt32(0);
				}
				ProcessResult(reader, nextIDDO, logCategory);
			} catch (Exception ex) {
				string errorMessage = Resource.GetErrorMessage(MessageKeys.NEXT_ID_CANNOT_READ_BY_PAGE, nextIDDO.Language, ex);
				throw new DataAccessException(errorMessage, ex, logCategory);
			} finally {
				if (reader != null) {
					reader.Close();
				}
			}
			return nextIDs;
		}

	}
}
