///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the 'Researched_Content'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using System.Text;
using System.EnterpriseServices;
using System.Reflection;


using FindMyFamilies.Data;
using FindMyFamilies.Util;
using FindMyFamilies.Exceptions;
using FindMyFamilies.DataAccess;

namespace FindMyFamilies.DataAccess {
	/// <summary>
	/// Purpose: Data Access class for the 'Researched_Content'.
	/// </summary>
	public class ResearchedContentDAO : ResearchedContentDAOBase {
		private static readonly object logCategory = System.Reflection.MethodBase.GetCurrentMethod().DeclaringType;
		// Stored Procedure Name Constants

		// Field Name Constants

		/// <summary>
		/// Purpose: Base Class constructor.
		/// </summary>
		public ResearchedContentDAO() : base() {
		}

		/// <summary>
		/// Purpose: Creates a new record in Researched_Content table and returns the generated primary key by reference.
		/// </summary>
		/// <param name = "researchedContentDO">ResearchedContentDO researchedContentDO</param>
		public override ResearchedContentDO CreateResearchedContent(ResearchedContentDO researchedContentDO) {
			return base.CreateResearchedContent(researchedContentDO);
		}

		/// <summary>
		/// Purpose: Update a record in Researched_Content.
		/// </summary>
		/// <param name = "researchedContentDO">ResearchedContentDO researchedContentDO</param>
		public override void UpdateResearchedContent(ResearchedContentDO researchedContentDO) {
			base.UpdateResearchedContent(researchedContentDO);
		}

		/// <summary>
		/// Purpose: Delete a record in Researched_Content.
		/// </summary>
		/// <param name = "researchedContentDO">ResearchedContentDO researchedContent</param>
		public override void DeleteResearchedContent(ResearchedContentDO researchedContentDO) {
			base.DeleteResearchedContent(researchedContentDO);
		}

		/// <summary>
		/// Purpose: Retrieve a record in Researched_Content table by primary key.
		/// </summary>
		/// <param name = "researchedContentDO">ResearchedContentDO researchedContentDO.</param>
		public override ResearchedContentDO ReadResearchedContent(ResearchedContentDO researchedContentDO) {
			return base.ReadResearchedContent(researchedContentDO);
		}

		/// <summary>
		/// Purpose: Retrieves all records in Researched_Content table.
		/// </summary>
		/// <param name = "dataTransferObject">DataTransferObject dataTransferObject.</param>
		public override ICollection ReadResearchedContentsAll(DataTransferObject dataTransferObject) {
			return base.ReadResearchedContentsAll(dataTransferObject);
		}

		/// <summary>
		/// Purpose: Retrieves all records from Researched_Content table for populating a list control.
		/// </summary>
		/// <param name = "dataTransferObject">DataTransferObject dataTransferObject</param>
		public override ICollection ReadResearchedContentsAllList(DataTransferObject dataTransferObject) {
			return base.ReadResearchedContentsAllList(dataTransferObject);
		}

		/// <summary>
		/// Purpose: Reads a page of records from table Researched_Content by search criteria.
		/// </summary>
		/// <returns>Returns a collection of ResearchedContents</returns>
		public virtual ICollection ReadResearchedContentsByPage(ResearchedContentDO researchedContentDO) {
			IList researchedContents = new ArrayList();
			IDataReader reader = null;
			try {
				IDataCommand command = dataSource.GetCommand(PagingDO.READ_BY_PAGE);
				command.SetParameter(PagingDO.PAGING_TABLE_NAME, TABLE_NAME);
				command.SetParameter(PagingDO.PAGING_PRIMARY_KEY, ResearchedContentDAO.RESEARCHED_CONTENT_ID);
				command.SetParameter(PagingDO.PAGING_FIELDS, "*");
				command.SetParameter(PagingDO.PAGING_ORDER, ResearchedContentDAO.RESEARCHED_CONTENT_ID);
				command.SetParameter(PagingDO.PAGING_PAGE_SIZE, researchedContentDO.Paging.PageSize);
				command.SetParameter(PagingDO.PAGING_PAGE_INDEX, researchedContentDO.Paging.PageIndex);
				command.SetParameter(PagingDO.PAGING_FILTER, ResearchedContentDAO.RESEARCHED_CONTENT_ID + " > 1");
				command.SetParameter(LANGUAGE, researchedContentDO.Language);
				reader = command.ExecuteReader();
		
				// populate the detail object from the SQL Server Data Reader
				while (reader.Read()) {
					researchedContents.Add(this.MapToDataTransferObject(reader));
				}
				if (reader.NextResult()) {
					reader.Read();
					if (researchedContents.Count < 1) {
						researchedContents.Add(new ResearchedContentDO());
					}
					((ResearchedContentDO)researchedContents[0]).Paging.TotalRecords = reader.GetInt32(0);
				}
				ProcessResult(reader, researchedContentDO, logCategory);
			} catch (Exception ex) {
				string errorMessage = Resource.GetErrorMessage(MessageKeys.RESEARCHED_CONTENT_CANNOT_READ_BY_PAGE, researchedContentDO.Language, ex);
				throw new DataAccessException(errorMessage, ex, logCategory);
			} finally {
				if (reader != null) {
					reader.Close();
				}
			}
			return researchedContents;
		}

	}
}
