///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the 'Translation'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;
using System.Text;
using System.EnterpriseServices;
using System.Reflection;


using FindMyFamilies.Data;
using FindMyFamilies.Util;
using FindMyFamilies.Exceptions;
using FindMyFamilies.DataAccess;

namespace FindMyFamilies.DataAccess {
	/// <summary>
	/// Purpose: Data Access class for the 'Translation'.
	/// </summary>
	public class TranslationDAO : TranslationDAOBase {
		private static readonly object logCategory = System.Reflection.MethodBase.GetCurrentMethod().DeclaringType;
		// Stored Procedure Name Constants

		// Field Name Constants

		/// <summary>
		/// Purpose: Base Class constructor.
		/// </summary>
		public TranslationDAO() : base() {
		}

		/// <summary>
		/// Purpose: Creates a new record in Translation table and returns the generated primary key by reference.
		/// </summary>
		/// <param name = "translationDO">TranslationDO translationDO</param>
		public override TranslationDO CreateTranslation(TranslationDO translationDO) {
			return base.CreateTranslation(translationDO);
		}

		/// <summary>
		/// Purpose: Update a record in Translation.
		/// </summary>
		/// <param name = "translationDO">TranslationDO translationDO</param>
		public override void UpdateTranslation(TranslationDO translationDO) {
			base.UpdateTranslation(translationDO);
		}

		/// <summary>
		/// Purpose: Delete a record in Translation.
		/// </summary>
		/// <param name = "translationDO">TranslationDO translation</param>
		public override void DeleteTranslation(TranslationDO translationDO) {
			base.DeleteTranslation(translationDO);
		}

		/// <summary>
		/// Purpose: RetrieveFamilySearchData a record in Translation table by primary key.
		/// </summary>
		/// <param name = "translationDO">TranslationDO translationDO.</param>
		public override TranslationDO ReadTranslation(TranslationDO translationDO) {
			return base.ReadTranslation(translationDO);
		}

		/// <summary>
		/// Purpose: Retrieves all records in Translation table.
		/// </summary>
		/// <param name = "dataTransferObject">DataTransferObject dataTransferObject.</param>
		public override ICollection ReadTranslationsAll(DataTransferObject dataTransferObject) {
			return base.ReadTranslationsAll(dataTransferObject);
		}

		/// <summary>
		/// Purpose: Retrieves all records from Translation table for populating a list control.
		/// </summary>
		/// <param name = "dataTransferObject">DataTransferObject dataTransferObject</param>
		public override ICollection ReadTranslationsAllList(DataTransferObject dataTransferObject) {
			return base.ReadTranslationsAllList(dataTransferObject);
		}

		/// <summary>
		/// Purpose: Reads a page of records from table Translation by search criteria.
		/// </summary>
		/// <returns>Returns a collection of Translations</returns>
		public virtual ICollection ReadTranslationsByPage(TranslationDO translationDO) {
			IList translations = new ArrayList();
			IDataReader reader = null;
			try {
				IDataCommand command = dataSource.GetCommand(PagingDO.READ_BY_PAGE);
				command.SetParameter(PagingDO.PAGING_TABLE_NAME, TABLE_NAME);
				command.SetParameter(PagingDO.PAGING_PRIMARY_KEY, TranslationDAO.TRANSLATION_ID);
				command.SetParameter(PagingDO.PAGING_FIELDS, "*");
				command.SetParameter(PagingDO.PAGING_ORDER, TranslationDAO.TRANSLATION_ID);
				command.SetParameter(PagingDO.PAGING_PAGE_SIZE, translationDO.Paging.PageSize);
				command.SetParameter(PagingDO.PAGING_PAGE_INDEX, translationDO.Paging.PageIndex);
				command.SetParameter(PagingDO.PAGING_FILTER, TranslationDAO.TRANSLATION_ID + " > 1");
				command.SetParameter(LANGUAGE, translationDO.Language);
				reader = command.ExecuteReader();
		
				// populate the detail object from the SQL Server Data Reader
				while (reader.Read()) {
					translations.Add(this.MapToDataTransferObject(reader));
				}
				if (reader.NextResult()) {
					reader.Read();
					if (translations.Count < 1) {
						translations.Add(new TranslationDO());
					}
					((TranslationDO)translations[0]).Paging.TotalRecords = reader.GetInt32(0);
				}
				ProcessResult(reader, translationDO, logCategory);
			} catch (Exception ex) {
				string errorMessage = Resource.GetErrorMessage(MessageKeys.TRANSLATION_CANNOT_READ_BY_PAGE, translationDO.Language, ex);
				throw new DataAccessException(errorMessage, ex, logCategory);
			} finally {
				if (reader != null) {
					reader.Close();
				}
			}
			return translations;
		}

	}
}
