///////////////////////////////////////////////////////////////////////////
// Description: Constants class
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;

namespace  FindMyFamilies.DataAccess
{
	/// <summary>
	/// Purpose: Constants class
	/// </summary>
	public class DBConstantsBase {
		public const string FIND_PERSON_OPTIONS_CREATE = "cl_FindPersonOptions_Create";
		public const string FIND_PERSON_OPTIONS_UPDATE = "cl_FindPersonOptions_Update";
		public const string FIND_PERSON_OPTIONS_DELETE = "cl_FindPersonOptions_Delete";
		public const string FIND_PERSON_OPTIONS_READ_ = "cl_FindPersonOptions_Read";
		public const string FIND_PERSON_OPTIONS_READ_ALL = "cl_FindPersonOptions_ReadAll";
		public const string FIND_PERSON_OPTIONS_READ_ALL_LIST = "cl_FindPersonOptions_ReadAllList";
		public const string ADDRESS_CREATE = "cl_Address_Create";
		public const string ADDRESS_UPDATE = "cl_Address_Update";
		public const string ADDRESS_DELETE = "cl_Address_Delete";
		public const string ADDRESS_READ_ = "cl_Address_Read";
		public const string ADDRESS_READ_ALL = "cl_Address_ReadAll";
		public const string ADDRESS_READ_ALL_LIST = "cl_Address_ReadAllList";
		public const string MEMBER_CREATE = "cl_Member_Create";
		public const string MEMBER_UPDATE = "cl_Member_Update";
		public const string MEMBER_DELETE = "cl_Member_Delete";
		public const string MEMBER_READ_ = "cl_Member_Read";
		public const string MEMBER_READ_ALL = "cl_Member_ReadAll";
		public const string MEMBER_READ_ALL_LIST = "cl_Member_ReadAllList";
	}
}
