///////////////////////////////////////////////////////////////////////////
// Description: AncestryServices Class
// generated by Generator v1.0.1635.8359 Final on: Wednesday, June 23, 2004, 5:41:55 AM
///////////////////////////////////////////////////////////////////////////

using System;
using FindMyFamilies.Data;
using FindMyFamilies.DataAccess;
using Gx;

namespace FindMyFamilies.BusinessObject {

    /// <summary>
    ///     Purpose: Business Object Class for Ancestry
    /// </summary>
    public class AncestryBO {

        public Gedcomx GetPersonAncestryWithSpouse(String personId, String spouseId, String generations, ref SessionDO session) {
            return new AncestryDAO().GetPersonAncestryWithSpouse(personId, spouseId, generations, ref session);
        }
    }

}