///////////////////////////////////////////////////////////////////////////
// Description: AuthenticationServices Class
// generated by Generator v1.0.1635.8359 Final on: Wednesday, June 23, 2004, 5:41:55 AM
///////////////////////////////////////////////////////////////////////////

using FindMyFamilies.DataAccess;
using FindMyFamilies.Data;
using FindMyFamilies.Util;

namespace FindMyFamilies.BusinessObject {

    /// <summary>
    ///     Purpose: Business Object Class for Authentication
    /// </summary>
    public class AuthenticationBO {
        private Logger logger = new Logger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public SessionDO Authenticate(string username, string password, string clientId) {
            return new AuthenticationDAO().Authenticate(username, password, clientId);
        }

        public SessionDO Authenticate(string username, string password, string clientId, string clientSecret) {
            return new AuthenticationDAO().Authenticate(username, password, clientId, clientSecret);
        }
    }

}