///////////////////////////////////////////////////////////////////////////
// Description: AppSettingsBase Class
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Specialized;
using System.Reflection;

using FindMyFamilies.Data;
using FindMyFamilies.Util;
using FindMyFamilies.Exceptions;
using FindMyFamilies.BusinessObject;

namespace findmyfamilies.Services {

	/// <summary>
	/// Purpose: Services Facade Base Class for AppSettingsBase
	/// </summary>
	public class AppSettingsBase {

		/// <summary>
		/// Purpose: Create a AppSettings
		/// </summary>
		/// <param name = "appSettingsDO">AppSettingsDO appSettingsDO</param>
		public virtual AppSettingsDO CreateAppSettings(AppSettingsDO appSettingsDO) {
			return AppSettingsBO.CreateAppSettings(appSettingsDO);
		}
		
		/// <summary>
		/// Purpose: Create AppSettingss
		/// </summary>
		/// <param name = "appSettingsDOs">ICollection appSettingsDOs</param>
		public virtual ICollection CreateAppSettingss(IList appSettingsDOs) {
			return AppSettingsBO.CreateAppSettingss(appSettingsDOs);
		}
		
		private static AppSettingsBO m_AppSettingsBO;
		
		public AppSettingsBO AppSettingsBO {
			get {
				if (m_AppSettingsBO == null) {
					AppSettingsBase appSettings = new AppSettingsBase();
					lock(appSettings) {
						m_AppSettingsBO = new AppSettingsBO();
					}
				}
				return m_AppSettingsBO;
			}
		}
		
		/// <summary>
		/// Purpose: Get a AppSettings with a primary key
		///      Must pass a App_Settings_ID in the data object
		/// </summary>
		/// <param name = "appSettingsDO">AppSettingsDO appSettingsDO</param>
		public virtual AppSettingsDO ReadAppSettings(AppSettingsDO appSettingsDO) {
			return AppSettingsBO.ReadAppSettings(appSettingsDO);
		}
		
		/// <summary>
		/// Purpose: Read all AppSettingss
		/// </summary>
		/// <returns>Returns a collection of AppSettings data objects</returns>
		/// <param name = "dataTransferObject">DataTransferObject dataTransferObject.</param>
		public virtual ICollection ReadAppSettingssAll(DataTransferObject dataTransferObject) {
			return AppSettingsBO.ReadAppSettingssAll(dataTransferObject);
		}
		
		/// <summary>
		/// Purpose: Read all AppSettingss for a list
		/// </summary>
		/// <returns>Returns a collection of ListItem data objects</returns>
		/// <param name = "dataTransferObject">DataTransferObject dataTransferObject.</param>
		public virtual ICollection ReadAppSettingssAllList(DataTransferObject dataTransferObject) {
			return AppSettingsBO.ReadAppSettingssAllList(dataTransferObject);
		}
		
		/// <summary>
		/// Purpose: Read AppSettingss by page
		/// </summary>
		/// <returns>Returns AppSettings data objects by page</returns>
		/// <param name = "appSettingsDO">AppSettingsDO appSettingsDO</param>
		public virtual ICollection ReadAppSettingssByPage(AppSettingsDO appSettingsDO) {
			return AppSettingsBO.ReadAppSettingssByPage(appSettingsDO);
		}
		
		/// <summary>
		/// Purpose: Update a AppSettings
		/// </summary>
		/// <param name = "appSettingsDO">AppSettingsDO appSettingsDO</param>
		public virtual void UpdateAppSettings(AppSettingsDO appSettingsDO) {
			AppSettingsBO.UpdateAppSettings(appSettingsDO);
		}
		
		/// <summary>
		/// Purpose: Update AppSettingss
		/// </summary>
		/// <param name = "appSettingsDOs">ICollection appSettingsDOs</param>
		public virtual void UpdateAppSettingss(IList appSettingsDOs) {
			AppSettingsBO.UpdateAppSettingss(appSettingsDOs);
		}
		
		/// <summary>
		/// Purpose: Delete a AppSettings
		/// </summary>
		/// <param name = "appSettingsDO">AppSettingsDO appSettingsDO</param>
		public virtual void DeleteAppSettings(AppSettingsDO appSettingsDO) {
			AppSettingsBO.DeleteAppSettings(appSettingsDO);
		}

		/// <summary>
		/// Purpose: Delete AppSettingss
		/// </summary>
		/// <param name = "appSettingsDOs">ICollection appSettingsDOs</param>
		public virtual void DeleteAppSettingss(IList appSettingsDOs) {
			AppSettingsBO.DeleteAppSettingss(appSettingsDOs);
		}
		
	}
}
