///////////////////////////////////////////////////////////////////////////
// Description: MemberServices Class
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Specialized;
using System.Reflection;


using FindMyFamilies.Data;
using FindMyFamilies.Util;
using FindMyFamilies.Exceptions;
using FindMyFamilies.BusinessObject;

namespace findmyfamilies.Services {

	/// <summary>
	/// Purpose: Services Facade Class for MemberServices
	/// </summary>
	public sealed class MemberServices : MemberServicesBase {

		private MemberServices() {
		}
		public static MemberServices Instance() {
			return Nested.instance;
		}
		
		class Nested {
			// Explicit static constructor to tell C# compiler
			// not to mark type as beforefieldinit
			static Nested() {
			}
		
			internal static readonly MemberServices instance = new MemberServices();
		}
		/// <summary>
		/// Purpose: Get a Member By a Member ID
		///      Must pass a Member_ID in the data object
		/// </summary>
		/// <param name = "memberDO">MemberDO memberDO</param>
		public MemberDO ReadMemberByMemberID(MemberDO memberDO) {
			return MemberBO.ReadMember(memberDO);
		}
	}


}
