// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Gx {

  /// <remarks>
  ///  &lt;p&gt;The GEDCOM X media types define the serialization formats of the GEDCOM X conceptual model. The canonical documentation
  ///  is provided by the formal specification documents:&lt;/p&gt;
  ///  
  ///  &lt;ul&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md&quot;&gt;The GEDCOM X Conceptual Model, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md&quot;&gt;The GEDCOM X JSON Format, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/xml-format-specification.md&quot;&gt;The GEDCOM X XML Format, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;/ul&gt;
  ///  
  ///  &lt;p&gt;This documentation is provided as a non-normative reference guide.&lt;/p&gt;
  /// </remarks>
  /// <summary>
  ///  &lt;p&gt;The GEDCOM X media types define the serialization formats of the GEDCOM X conceptual model. The canonical documentation
  ///  is provided by the formal specification documents:&lt;/p&gt;
  ///  
  ///  &lt;ul&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md&quot;&gt;The GEDCOM X Conceptual Model, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md&quot;&gt;The GEDCOM X JSON Format, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;li&gt;&lt;a href=&quot;https://github.com/FamilySearch/gedcomx/blob/master/specifications/xml-format-specification.md&quot;&gt;The GEDCOM X XML Format, Version 1.0&lt;/a&gt;&lt;/li&gt;
  ///  &lt;/ul&gt;
  ///  
  ///  &lt;p&gt;This documentation is provided as a non-normative reference guide.&lt;/p&gt;
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="Gedcomx")]
  [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="Gedcomx")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://gedcomx.org/v1/",ElementName="gedcomx")]
  public partial class GedcomxPerson : Gx.Links.HypermediaEnabledData {

    private System.Collections.Generic.List<Gx.Conclusion.Person> _persons;
    private System.Collections.Generic.List<Gx.Conclusion.Relationship> _relationships;
    /// <summary>
    ///  The persons included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="person",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="person")]
    public System.Collections.Generic.List<Gx.Conclusion.Person> Persons {
      get {
        return this._persons;
      }
      set {
        this._persons = value;
      }
    }
    /// <summary>
    ///  The relationships included in this genealogical data set.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="relationship",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="relationship")]
    public System.Collections.Generic.List<Gx.Conclusion.Relationship> Relationships {
      get {
        return this._relationships;
      }
      set {
        this._relationships = value;
      }
    }
  }
}  
