// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Gx.Types {

  /// <remarks>
  ///  Enumeration of standard name part types.
  /// </remarks>
  /// <summary>
  ///  Enumeration of standard name part types.
  /// </summary>
  public enum PartType {

    /// <summary>
    ///  Unspecified enum value.
    /// </summary>
    [System.Xml.Serialization.XmlEnumAttribute(Name="__NULL__")]
    [System.Xml.Serialization.SoapEnumAttribute(Name="__NULL__")]
    NULL,

    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    Prefix,

    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    Suffix,

    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    Given,

    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    Surname,

    /// <summary>
    ///  (no documentation provided)
    /// </summary>
    OTHER
  }

  /// <remarks>
  /// Utility class for converting to/from the QNames associated with PartType.
  /// </remarks>
  /// <summary>
  /// Utility class for converting to/from the QNames associated with PartType.
  /// </summary>
  public static class PartTypeQNameUtil {

    /// <summary>
    /// Get the known PartType for a given QName. If the QName isn't a known QName, PartType.OTHER will be returned.
    /// </summary>
    public static PartType ConvertFromKnownQName(string qname) {
      if (qname != null) {
        if ("http://gedcomx.org/Prefix".Equals(qname)) {
          return PartType.Prefix;
        }
        if ("http://gedcomx.org/Suffix".Equals(qname)) {
          return PartType.Suffix;
        }
        if ("http://gedcomx.org/Given".Equals(qname)) {
          return PartType.Given;
        }
        if ("http://gedcomx.org/Surname".Equals(qname)) {
          return PartType.Surname;
        }
      }
      return PartType.OTHER;
    }

    /// <summary>
    /// Convert the known PartType to a QName. If PartType.OTHER, an ArgumentException will be thrown.
    /// </summary>
    public static string ConvertToKnownQName(PartType known) {
      switch (known) {
        case PartType.Prefix:
          return "http://gedcomx.org/Prefix";
        case PartType.Suffix:
          return "http://gedcomx.org/Suffix";
        case PartType.Given:
          return "http://gedcomx.org/Given";
        case PartType.Surname:
          return "http://gedcomx.org/Surname";
        default:
          throw new System.ArgumentException("No known QName for: " + known, "known");
      }
    }
  }
}
