// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>
using System;

namespace Gx.Conclusion {

  /// <remarks>
  ///  A part of a name.
  /// </remarks>
  /// <summary>
  ///  A part of a name.
  /// </summary>
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="part")]
  [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gedcomx.org/v1/",TypeName="part")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://gedcomx.org/v1/",ElementName="part")]
  public partial class Part : Gx.Common.ExtensibleData {

    private string _value;
    private string _type;
    private System.Collections.Generic.List<Gx.Records.Field> _fields;
    private System.Collections.Generic.List<Gx.Common.Qualifier> _qualifiers;
    /// <summary>
    ///  The value of the name part.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="value")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="value")]
    public string value {
      get {
        return this._value;
      }
      set {
        this._value = value;
      }
    }
    /// <summary>
    ///  The type of the name part.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="type")]
    [System.Xml.Serialization.SoapAttributeAttribute(AttributeName="type")]
    public string Type {
      get {
        return this._type;
      }
      set {
        this._type = value;
      }
    }

    /// <summary>
    ///  Convenience property for treating Type as an enum. See Gx.Types.PartTypeQNameUtil for details on getter/setter functionality.
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute]
    public Gx.Types.PartType KnownType {
      get {
        return Gx.Types.PartTypeQNameUtil.ConvertFromKnownQName(this._type);
      }
      set {
        this._type = Gx.Types.PartTypeQNameUtil.ConvertToKnownQName(value);
      }
    }
    /// <summary>
    ///  The references to the record fields being used as evidence.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="field",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="field")]
    public System.Collections.Generic.List<Gx.Records.Field> Fields {
      get {
        return this._fields;
      }
      set {
        this._fields = value;
      }
    }
    /// <summary>
    ///  The qualifiers associated with this name part.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(ElementName="qualifier",Namespace="http://gedcomx.org/v1/")]
    [System.Xml.Serialization.SoapElementAttribute(ElementName="qualifier")]
    public System.Collections.Generic.List<Gx.Common.Qualifier> Qualifiers {
      get {
        return this._qualifiers;
      }
      set {
        this._qualifiers = value;
      }
    }
  }
}  
