// <auto-generated>
// 
//
// Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml.Serialization;
using Gx.Records;

namespace Gx.Conclusion {

    /// <remarks>
    ///     A person.
    /// </remarks>
    /// <summary>
    ///     A person.
    /// </summary>
    [Serializable]
    [XmlType(Namespace = "http://gedcomx.org/v1/", TypeName = "Person")]
    [SoapType(Namespace = "http://gedcomx.org/v1/", TypeName = "Person")]
    [XmlRoot(Namespace = "http://gedcomx.org/v1/", ElementName = "person")]
    public class Person : Subject {

        private DisplayProperties _display;
        private List<Fact> _facts;
        private Gender _gender;
        private bool? _living;
        private List<Name> _names;


        /// <summary>
        ///     Living status of the person as treated by the system.
        /// </summary>
        [XmlElement(ElementName = "living", Namespace = "http://gedcomx.org/v1/")]
        [SoapElement(ElementName = "living")]
        public bool Living {
            get {
                return _living.GetValueOrDefault();
            }
            set {
                _living = value;
            }
        }

        /// <summary>
        ///     The gender conclusion for the person.
        /// </summary>
        [XmlElement(ElementName = "gender", Namespace = "http://gedcomx.org/v1/")]
        [SoapElement(ElementName = "gender")]
        public Gender Gender {
            get {
                return _gender;
            }
            set {
                _gender = value;
            }
        }

        /// <summary>
        ///     The name conclusions for the person.
        /// </summary>
        [XmlElement(ElementName = "name", Namespace = "http://gedcomx.org/v1/")]
        [SoapElement(ElementName = "name")]
        public List<Name> Names {
            get {
                return _names;
            }
            set {
                _names = value;
            }
        }

        /// <summary>
        ///     The fact conclusions for the person.
        /// </summary>
        [XmlElement(ElementName = "fact", Namespace = "http://gedcomx.org/v1/")]
        [SoapElement(ElementName = "fact")]
        public List<Fact> Facts {
            get {
                return _facts;
            }
            set {
                _facts = value;
            }
        }

        /// <summary>
        ///     Display properties for the person. Display properties are not specified by GEDCOM X core, but as extension elements
        ///     by GEDCOM X RS.
        /// </summary>
        [XmlElement(ElementName = "display", Namespace = "http://gedcomx.org/v1/")]
        [SoapElement(ElementName = "display")]
        public DisplayProperties Display {
            get {
                return _display;
            }
            set {
                _display = value;
            }
        }

    }
}