///////////////////////////////////////////////////////////////////////////
// Description: Data Object Base for the 'App_Settings'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;

using FindMyFamilies.Util;
using FindMyFamilies.Data;
using ProtoBuf;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.Data {

	/// <summary>
	/// Purpose: DataTransferObject Base class for the 'App_Settings'.
	/// </summary>
	[ProtoContract(ImplicitFields = ImplicitFields.AllFields, AsReferenceDefault = true)]

	public class AppSettingsDOBase : DataTransferObject {

		// AppSettings Constants
		// AppSettings Constants
		public const string TABLE_NAME = "APP_SETTINGS";
		public const string APP_SETTINGS_ID = "AppSettingsID";
		public const string MEMBER_ID = "MemberID";
		public const string SETTINGS = "Settings";
		public const string LANGUAGE_ID = "LanguageID";

		// Property Declarations
		private int		m_AppSettingsID;  // App_Settings_ID
		private int		m_MemberID;  // Member_ID
		private string	m_Settings;  // Settings
		private string	m_LanguageID;  // Language_ID

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public AppSettingsDOBase() {
			this.Settings = Constants.LANGUAGE_DEFAULT;
			this.LanguageID = Constants.LANGUAGE_DEFAULT;
		}


		// Class Property Declarations
		/// <summary>
		/// SQLFieldName: App_Settings_ID
		/// </summary>
		public int AppSettingsID {
			get {
				return m_AppSettingsID;
			}
			set {
				m_AppSettingsID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Member_ID
		/// </summary>
		public int MemberID {
			get {
				return m_MemberID;
			}
			set {
				m_MemberID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Settings
		/// </summary>
		public string Settings {
			get {
				return GetDefaultValue(m_Settings);
			}
			set {
				m_Settings = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Language_ID
		/// </summary>
		public string LanguageID {
			get {
				return GetDefaultValue(m_LanguageID);
			}
			set {
				m_LanguageID = value;
			}
		}

	}
}
