///////////////////////////////////////////////////////////////////////////
// Description: Data Object Base for the 'Find_Person_Options'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;

using FindMyFamilies.Util;
using FindMyFamilies.Data;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.Data {

	/// <summary>
	/// Purpose: DataTransferObject Base class for the 'Find_Person_Options'.
	/// </summary>
	public class FindPersonOptionsDOBase : DataTransferObject {

		// FindPersonOptions Constants
		// FindPersonOptions Constants
		public const string TABLE_NAME = "FIND_PERSON_OPTIONS";
		public const string FIND_PERSON_OPTIONS_ID = "FindPersonOptionsID";
		public const string DATE_CREATED = "DateCreated";
		public const string PERSON_ID = "PersonID";
		public const string OPTION_CODE = "OptionCode";
		public const string OPTION_DESCRIPTION = "OptionDescription";
		public const string OPTION_ORDER = "OptionOrder";
		public const string LANGUAGE_ID = "LanguageID";

		// Property Declarations
		private int		m_FindPersonOptionsID;  // Find_Person_Options_ID
		private DateTime	m_DateCreated;  // Date_Created
		private string	m_PersonID;  // Person_ID
		private string	m_OptionCode;  // Option_Code
		private string	m_OptionDescription;  // Option_Description
		private string	m_OptionOrder;  // Option_Order
		private string	m_LanguageID;  // Language_ID

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public FindPersonOptionsDOBase() {
			this.LanguageID = Constants.LANGUAGE_DEFAULT;
		}


		// Class Property Declarations
		/// <summary>
		/// SQLFieldName: Find_Person_Options_ID
		/// </summary>
		public int FindPersonOptionsID {
			get {
				return m_FindPersonOptionsID;
			}
			set {
				m_FindPersonOptionsID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Date_Created
		/// </summary>
		public DateTime DateCreated {
			get {
				return GetDefaultValue(m_DateCreated);
			}
			set {
				m_DateCreated = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Person_ID
		/// </summary>
		public string PersonID {
			get {
				return GetDefaultValue(m_PersonID);
			}
			set {
				m_PersonID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Option_Code
		/// </summary>
		public string OptionCode {
			get {
				return GetDefaultValue(m_OptionCode);
			}
			set {
				m_OptionCode = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Option_Description
		/// </summary>
		public string OptionDescription {
			get {
				return GetDefaultValue(m_OptionDescription);
			}
			set {
				m_OptionDescription = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Option_Order
		/// </summary>
		public string OptionOrder {
			get {
				return GetDefaultValue(m_OptionOrder);
			}
			set {
				m_OptionOrder = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Language_ID
		/// </summary>
		public string LanguageID {
			get {
				return GetDefaultValue(m_LanguageID);
			}
			set {
				m_LanguageID = value;
			}
		}

	}
}

