using System;
///////////////////////////////////////////////////////////////////////////
// Description: Data Base class for the table 'LISTS'
// generated by Generator v1.0.1287.11424 Final on: Friday, July 11, 2003, 7:23:44 AM
///////////////////////////////////////////////////////////////////////////
namespace FindMyFamilies.Data {
    /// <summary>
    /// Purpose: Data Base class for the table 'LISTS' .
    /// </summary>
    public class ListsBase {
        public const string LIST_ID = "listID";
        public const string LIST_NAME = "listName";
        public const string FIELD_NAME = "fieldName";
        public const string FIELD_VALUE = "fieldValue";

        private int     m_listID;  // list_id
        private string  m_listName;  // list_name
        private string  m_fieldName;  // field_name
        private string  m_fieldValue;  // field_value

        /// <summary>
        /// Purpose: Class constructor.
        /// </summary>
        public ListsBase() {
            init();
        }

        public ListsBase(int listID) {
            this.ListID = listID;
            init();
        }

        public void init() {

        }


        public int ListID {
            get {
                return m_listID;
            }
            set {
                m_listID = value;
            }
        }

        public string ListName {
            get {
                return m_listName;
            }
            set {
                m_listName = value;
            }
        }

        public string FieldName {
            get {
                return m_fieldName;
            }
            set {
                m_fieldName = value;
            }
        }

        public string FieldValue {
            get {
                return m_fieldValue;
            }
            set {
                m_fieldValue = value;
            }
        }

    }
}
