///////////////////////////////////////////////////////////////////////////
// Description: Data Object Base for the 'Member'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;

using FindMyFamilies.Util;
using FindMyFamilies.Data;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.Data {

	/// <summary>
	/// Purpose: DataTransferObject Base class for the 'Member'.
	/// </summary>
	public class MemberDOBase : DataTransferObject {

		// Member Constants
		// Member Constants
		public const string TABLE_NAME = "MEMBER";
		public const string MEMBER_ID = "MemberID";
		public const string PERSON_ID = "PersonID";
		public const string MAILING_ADDRESS_ID = "MailingAddressID";
		public const string MEMBER_TYPE = "MemberType";
		public const string MEMBER_STATUS = "MemberStatus";
		public const string FIRSTNAME = "Firstname";
		public const string MIDDLENAME = "Middlename";
		public const string LASTNAME = "Lastname";
		public const string EMAIL = "Email";
		public const string BIRTH_DATE = "BirthDate";
		public const string PASSWORD = "Password";
		public const string DATE_CREATED = "DateCreated";
		public const string DISPLAY_NAME = "DisplayName";
		public const string NOTES = "Notes";
		public const string LANGUAGE_ID = "LanguageID";

		// Property Declarations
		private int		m_MemberID;  // Member_ID
		private string	m_PersonID;  // Person_ID
		private int		m_MailingAddressID;  // Mailing_Address_ID
		private string	m_MemberType;  // Member_Type
		private string	m_MemberStatus;  // Member_Status
		private string	m_Firstname;  // Firstname
		private string	m_Middlename;  // Middlename
		private string	m_Lastname;  // Lastname
		private string	m_Email;  // Email
		private DateTime	m_BirthDate;  // Birth_Date
		private string	m_Password;  // Password
		private DateTime	m_DateCreated;  // Date_Created
		private string	m_DisplayName;  // Display_Name
		private string	m_Notes;  // Notes
		private string	m_LanguageID;  // Language_ID

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public MemberDOBase() {
		}


		// Class Property Declarations
		/// <summary>
		/// SQLFieldName: Member_ID
		/// </summary>
		public int MemberID {
			get {
				return m_MemberID;
			}
			set {
				m_MemberID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Person_ID
		/// </summary>
		public string PersonID {
			get {
				return GetDefaultValue(m_PersonID);
			}
			set {
				m_PersonID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Mailing_Address_ID
		/// </summary>
		public int MailingAddressID {
			get {
				return m_MailingAddressID;
			}
			set {
				m_MailingAddressID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Member_Type
		/// </summary>
		public string MemberType {
			get {
				return GetDefaultValue(m_MemberType);
			}
			set {
				m_MemberType = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Member_Status
		/// </summary>
		public string MemberStatus {
			get {
				return GetDefaultValue(m_MemberStatus);
			}
			set {
				m_MemberStatus = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Firstname
		/// </summary>
		public string Firstname {
			get {
				return GetDefaultValue(m_Firstname);
			}
			set {
				m_Firstname = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Middlename
		/// </summary>
		public string Middlename {
			get {
				return GetDefaultValue(m_Middlename);
			}
			set {
				m_Middlename = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Lastname
		/// </summary>
		public string Lastname {
			get {
				return GetDefaultValue(m_Lastname);
			}
			set {
				m_Lastname = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Email
		/// </summary>
		public string Email {
			get {
				return GetDefaultValue(m_Email);
			}
			set {
				m_Email = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Birth_Date
		/// </summary>
		public DateTime BirthDate {
			get {
				return GetDefaultValue(m_BirthDate);
			}
			set {
				m_BirthDate = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Password
		/// </summary>
		public string Password {
			get {
				return GetDefaultValue(m_Password);
			}
			set {
				m_Password = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Date_Created
		/// </summary>
		public DateTime DateCreated {
			get {
				return GetDefaultValue(m_DateCreated);
			}
			set {
				m_DateCreated = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Display_Name
		/// </summary>
		public string DisplayName {
			get {
				return GetDefaultValue(m_DisplayName);
			}
			set {
				m_DisplayName = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Notes
		/// </summary>
		public string Notes {
			get {
				return GetDefaultValue(m_Notes);
			}
			set {
				m_Notes = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Language_ID
		/// </summary>
		public string LanguageID {
			get {
				return GetDefaultValue(m_LanguageID);
			}
			set {
				m_LanguageID = value;
			}
		}

	}
}
