///////////////////////////////////////////////////////////////////////////
// Description: Data Object Base for the 'Next_ID'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;

using FindMyFamilies.Util;
using FindMyFamilies.Data;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.Data {

	/// <summary>
	/// Purpose: DataTransferObject Base class for the 'Next_ID'.
	/// </summary>
	public class NextIDDOBase : DataTransferObject {

		// NextID Constants
		public const string TABLE_NAME = "NEXT_ID";
		public const string TABLE_ID = "TableID";
		public const string NEXT_VAL = "NextVal";
		public const string LANGUAGE_ID = "LanguageID";

		// Property Declarations
		private string	m_TableID;  // Table_ID
		private int		m_NextVal;  // Next_Val
		private string	m_LanguageID;  // Language_ID

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public NextIDDOBase() {
		}


		// Class Property Declarations
		/// <summary>
		/// SQLFieldName: Table_ID
		/// </summary>
		public string TableID {
			get {
				return GetDefaultValue(m_TableID);
			}
			set {
				m_TableID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Next_Val
		/// </summary>
		public int NextVal {
			get {
				return m_NextVal;
			}
			set {
				m_NextVal = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Language_ID
		/// </summary>
		public string LanguageID {
			get {
				return GetDefaultValue(m_LanguageID);
			}
			set {
				m_LanguageID = value;
			}
		}

	}
}
