///////////////////////////////////////////////////////////////////////////
// Description: Data Object Base for the 'Report'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;

using FindMyFamilies.Util;
using FindMyFamilies.Data;
using ProtoBuf;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.Data {

	/// <summary>
	/// Purpose: DataTransferObject Base class for the 'Report'.
	/// </summary>
	[ProtoContract(ImplicitFields = ImplicitFields.AllFields, AsReferenceDefault = true)]

	public class ReportDOBase : DataTransferObject {

		// Report Constants
		public const string TABLE_NAME = "REPORT";
		public const string REPORT_ID = "ReportID";
		public const string REPORT_DATE = "ReportDate";
		public const string LANGUAGE_ID = "LanguageID";
		public const string USER_ID = "UserID";
		public const string PERSON_ID = "PersonID";
		public const string PERSON_NAME = "PersonName";
		public const string REPORT_FILE = "ReportFile";
		public const string REPORT_DESCRIPTION = "ReportDescription";
		public const string RECORDS = "Records";
		public const string RESEARCH_TYPE = "ResearchType";
		public const string GENERATION = "Generation";

		// Property Declarations
		private int		m_ReportID;  // Report_ID
		private DateTime	m_ReportDate;  // Report_Date
		private string	m_LanguageID;  // Language_ID
		private string	m_UserID;  // User_ID
		private string	m_PersonID;  // Person_ID
		private string	m_PersonName;  // Person_Name
		private string	m_ReportFile;  // Report_File
		private string	m_ReportDescription;  // Report_Description
		private string	m_Records;  // Records
		private string	m_ResearchType;  // Research_Type
		private string	m_Generation;  // Generation

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public ReportDOBase() {
		}


		// Class Property Declarations
		/// <summary>
		/// SQLFieldName: Report_ID
		/// </summary>
		public int ReportID {
			get {
				return m_ReportID;
			}
			set {
				m_ReportID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Report_Date
		/// </summary>
		public DateTime ReportDate {
			get {
				return GetDefaultValue(m_ReportDate);
			}
			set {
				m_ReportDate = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Language_ID
		/// </summary>
		public string LanguageID {
			get {
				return GetDefaultValue(m_LanguageID);
			}
			set {
				m_LanguageID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: User_ID
		/// </summary>
		public string UserID {
			get {
				return GetDefaultValue(m_UserID);
			}
			set {
				m_UserID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Person_ID
		/// </summary>
		public string PersonID {
			get {
				return GetDefaultValue(m_PersonID);
			}
			set {
				m_PersonID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Person_Name
		/// </summary>
		public string PersonName {
			get {
				return GetDefaultValue(m_PersonName);
			}
			set {
				m_PersonName = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Report_File
		/// </summary>
		public string ReportFile {
			get {
				return GetDefaultValue(m_ReportFile);
			}
			set {
				m_ReportFile = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Report_Description
		/// </summary>
		public string ReportDescription {
			get {
				return GetDefaultValue(m_ReportDescription);
			}
			set {
				m_ReportDescription = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Records
		/// </summary>
		public string Records {
			get {
				return GetDefaultValue(m_Records);
			}
			set {
				m_Records = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Research_Type
		/// </summary>
		public string ResearchType {
			get {
				return GetDefaultValue(m_ResearchType);
			}
			set {
				m_ResearchType = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Generation
		/// </summary>
		public string Generation {
			get {
				return GetDefaultValue(m_Generation);
			}
			set {
				m_Generation = value;
			}
		}

	}
}

