///////////////////////////////////////////////////////////////////////////
// Description: Data Object Base for the 'Report'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;

using FindMyFamilies.Util;
using FindMyFamilies.Data;
using ProtoBuf;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.Data {

	/// <summary>
	/// Purpose: DataTransferObject Base class for the 'Report'.
	/// </summary>
    [ProtoContract(ImplicitFields = ImplicitFields.AllFields, AsReferenceDefault = true)]
	public class ReportDOBase : DataTransferObject {

		// Report Constants
		public const string TABLE_NAME = "REPORT";
		public const string REPORT_ID = "ReportId";
		public const string REPORT_DATE = "ReportDate";
		public const string LANGUAGE_ID = "LanguageID";
		public const string REPORT_BY = "ReportBy";
		public const string REPORT_FILE = "ReportFile";
		public const string REPORT_DESCRIPTION = "ReportTitle";
		public const string EMAILED = "Emailed";
		public const string PRIVATE = "Private";
		public const string PRIVATE_VIEW = "PrivateView";
		public const string REPORT_TYPE = "ReportType";

		// Property Declarations
		private int		m_ReportID;  // Report_ID
		private DateTime	m_ReportDate;  // Report_Date
		private string	m_LanguageID;  // Language_ID
		private string	m_ReportBy;  // Report_By
		private string	m_ReportFile;  // Report_File
		private string	m_ReportDescription;  // Report_Description
		private bool		m_Emailed;  // Emailed
		private string	m_Private;  // Private
		private string	m_PrivateView;  // Private_View
		private string	m_ReportType;  // Report_Type

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public ReportDOBase() {
		}


		// Class Property Declarations
		/// <summary>
		/// SQLFieldName: Report_ID
		/// </summary>
		public int ReportId {
			get {
				return m_ReportID;
			}
			set {
				m_ReportID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Report_Date
		/// </summary>
        public DateTime ReportDate {
			get {
				return GetDefaultValue(m_ReportDate);
			}
			set {
				m_ReportDate = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Language_ID
		/// </summary>
        public string LanguageID {
			get {
				return GetDefaultValue(m_LanguageID);
			}
			set {
				m_LanguageID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Report_By
		/// </summary>
        public string ReportBy {
			get {
				return GetDefaultValue(m_ReportBy);
			}
			set {
				m_ReportBy = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Report_File
		/// </summary>
        public string ReportFile {
			get {
				return GetDefaultValue(m_ReportFile);
			}
			set {
				m_ReportFile = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Report_Description
		/// </summary>
        public string ReportDescription {
			get {
				return GetDefaultValue(m_ReportDescription);
			}
			set {
				m_ReportDescription = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Emailed
		/// </summary>
        public bool Emailed {
			get {
				return m_Emailed;
			}
			set {
				m_Emailed = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Private
		/// </summary>
        public string Private {
			get {
				return GetDefaultValue(m_Private);
			}
			set {
				m_Private = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Private_View
		/// </summary>
        public string PrivateView {
			get {
				return GetDefaultValue(m_PrivateView);
			}
			set {
				m_PrivateView = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Report_Type
		/// </summary>
        public string ReportType {
			get {
				return GetDefaultValue(m_ReportType);
			}
			set {
				m_ReportType = value;
			}
		}

	}
}
