///////////////////////////////////////////////////////////////////////////
// Description: Data Object Base for the 'Researched_Content'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;

using FindMyFamilies.Util;
using FindMyFamilies.Data;
using ProtoBuf;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.Data {

	/// <summary>
	/// Purpose: DataTransferObject Base class for the 'Researched_Content'.
	/// </summary>
	[ProtoContract(ImplicitFields = ImplicitFields.AllFields, AsReferenceDefault = true)]

	public class ResearchedContentDOBase : DataTransferObject {

		// ResearchedContent Constants
		// ResearchedContent Constants
		public const string TABLE_NAME = "RESEARCHED_CONTENT";
		public const string RESEARCHED_CONTENT_ID = "ResearchedContentID";
		public const string CONTENT = "Content";
		public const string LANGUAGE_ID = "LanguageID";

		// Property Declarations
		private int		m_ResearchedContentID;  // Researched_Content_ID
		private string	m_Content;  // Content
		private string	m_LanguageID;  // Language_ID

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public ResearchedContentDOBase() {
			this.LanguageID = Constants.LANGUAGE_DEFAULT;
		}


		// Class Property Declarations
		/// <summary>
		/// SQLFieldName: Researched_Content_ID
		/// </summary>
		public int ResearchedContentID {
			get {
				return m_ResearchedContentID;
			}
			set {
				m_ResearchedContentID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Content
		/// </summary>
		public string Content {
			get {
				return GetDefaultValue(m_Content);
			}
			set {
				m_Content = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Language_ID
		/// </summary>
		public string LanguageID {
			get {
				return GetDefaultValue(m_LanguageID);
			}
			set {
				m_LanguageID = value;
			}
		}

	}
}
