///////////////////////////////////////////////////////////////////////////
// Description: Data Object Base for the 'Translation_Detail'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;

using FindMyFamilies.Util;
using FindMyFamilies.Data;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.Data {

	/// <summary>
	/// Purpose: DataTransferObject Base class for the 'Translation_Detail'.
	/// </summary>
	public class TranslationDetailDOBase : DataTransferObject {

		// TranslationDetail Constants
		public const string TABLE_NAME = "TRANSLATION_DETAIL";
		public const string TRANSLATION_DETAIL_ID = "TranslationDetailID";
		public const string TRANSLATION_DETAIL_DESCRIPTION = "TranslationDetailDescription";
		public const string TRANSLATION_DETAIL_KEY = "TranslationDetailKey";
		public const string TRANSLATION_DETAIL_TYPE = "TranslationDetailType";
		public const string TRANSLATION_MASTER_ID = "TranslationMasterID";
		public const string LANGUAGE_ID = "LanguageID";

		// Property Declarations
		private int		m_TranslationDetailID;  // Translation_Detail_ID
		private string	m_TranslationDetailDescription;  // Translation_Detail_Description
		private string	m_TranslationDetailKey;  // Translation_Detail_Key
		private string	m_TranslationDetailType;  // Translation_Detail_Type
		private int		m_TranslationMasterID;  // Translation_Master_ID
		private string	m_LanguageID;  // Language_ID

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public TranslationDetailDOBase() {
			this.LanguageID = Constants.LANGUAGE_DEFAULT;
		}


		// Class Property Declarations
		/// <summary>
		/// SQLFieldName: Translation_Detail_ID
		/// </summary>
		public int TranslationDetailID {
			get {
				return m_TranslationDetailID;
			}
			set {
				m_TranslationDetailID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Translation_Detail_Description
		/// </summary>
		public string TranslationDetailDescription {
			get {
				return GetDefaultValue(m_TranslationDetailDescription);
			}
			set {
				m_TranslationDetailDescription = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Translation_Detail_Key
		/// </summary>
		public string TranslationDetailKey {
			get {
				return GetDefaultValue(m_TranslationDetailKey);
			}
			set {
				m_TranslationDetailKey = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Translation_Detail_Type
		/// </summary>
		public string TranslationDetailType {
			get {
				return GetDefaultValue(m_TranslationDetailType);
			}
			set {
				m_TranslationDetailType = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Translation_Master_ID
		/// </summary>
		public int TranslationMasterID {
			get {
				return m_TranslationMasterID;
			}
			set {
				m_TranslationMasterID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Language_ID
		/// </summary>
		public string LanguageID {
			get {
				return GetDefaultValue(m_LanguageID);
			}
			set {
				m_LanguageID = value;
			}
		}

	}
}
