///////////////////////////////////////////////////////////////////////////
// Description: Data Object Base for the 'Translation'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;

using FindMyFamilies.Util;
using FindMyFamilies.Data;

// Please do not modify any code in this auto generated class.  This code will be overwritten when the generator is executed.
namespace FindMyFamilies.Data {

	/// <summary>
	/// Purpose: DataTransferObject Base class for the 'Translation'.
	/// </summary>
	public class TranslationDOBase : DataTransferObject {

		// Translation Constants
		public const string TABLE_NAME = "TRANSLATION";
		public const string TRANSLATION_ID = "TranslationID";
		public const string TRANSLATION_DETAIL_ID = "TranslationDetailID";
		public const string TRANSLATION_TEXT = "TranslationText";
		public const string LANGUAGE_ID = "LanguageID";

		// Property Declarations
		private int		m_TranslationID;  // Translation_ID
		private int		m_TranslationDetailID;  // Translation_Detail_ID
		private string	m_TranslationText;  // Translation_Text
		private string	m_LanguageID;  // Language_ID

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public TranslationDOBase() {
			this.LanguageID = Constants.LANGUAGE_DEFAULT;
		}


		// Class Property Declarations
		/// <summary>
		/// SQLFieldName: Translation_ID
		/// </summary>
		public int TranslationID {
			get {
				return m_TranslationID;
			}
			set {
				m_TranslationID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Translation_Detail_ID
		/// </summary>
		public int TranslationDetailID {
			get {
				return m_TranslationDetailID;
			}
			set {
				m_TranslationDetailID = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Translation_Text
		/// </summary>
		public string TranslationText {
			get {
				return GetDefaultValue(m_TranslationText);
			}
			set {
				m_TranslationText = value;
			}
		}

		/// <summary>
		/// SQLFieldName: Language_ID
		/// </summary>
		public string LanguageID {
			get {
				return GetDefaultValue(m_LanguageID);
			}
			set {
				m_LanguageID = value;
			}
		}

	}
}
