///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'Address'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'Address'.
	/// </summary>
	public class AddressDO : AddressDOBase {

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public AddressDO() : base() {
		}

		public AddressDO(int AddressID) : base() {
			this.AddressID = AddressID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
