///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'App_Settings'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'App_Settings'.
	/// </summary>
	public class AppSettingsDO : AppSettingsDOBase {

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public AppSettingsDO() : base() {
		}

		public AppSettingsDO(int AppSettingsID) : base() {
			this.AppSettingsID = AppSettingsID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
