///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'Email'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'Email'.
	/// </summary>
	public class EmailDO : EmailDOBase {

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public EmailDO() : base() {
		}

		public EmailDO(int EmailID) : base() {
			this.EmailID = EmailID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
