///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'Find_Person_Options'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'Find_Person_Options'.
	/// </summary>
	public class FindPersonOptionsDO : FindPersonOptionsDOBase {

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public FindPersonOptionsDO() : base() {
		}

		public FindPersonOptionsDO(int FindPersonOptionsID) : base() {
			this.FindPersonOptionsID = FindPersonOptionsID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
