///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'Member'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'Member'.
	/// </summary>
	public class MemberDO : MemberDOBase {

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public MemberDO() : base() {
		}

		public MemberDO(int MemberID) : base() {
			this.MemberID = MemberID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
