///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'Next_ID'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'Next_ID'.
	/// </summary>
	public class NextIDDO : NextIDDOBase {

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public NextIDDO() : base() {
		}

		public NextIDDO(string TableID) : base() {
			this.TableID = TableID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
