///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'Report'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;
using ProtoBuf;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'Report'.
	/// </summary>
    [ProtoContract(ImplicitFields = ImplicitFields.AllFields, AsReferenceDefault = true)]
	public class ReportDO : ReportDOBase {

   		public const string READ_REPORTS_BY_USER = "ReadReportsByUser";
   		public const string READ_REPORTS_LIST = "ReadReportsList";

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public ReportDO() : base() {
		}

		public ReportDO(int ReportID) : base() {
			this.ReportID = ReportID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
