///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'Researched_Content'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'Researched_Content'.
	/// </summary>
	public class ResearchedContentDO : ResearchedContentDOBase {

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public ResearchedContentDO() : base() {
		}

		public ResearchedContentDO(int ResearchedContentID) : base() {
			this.ResearchedContentID = ResearchedContentID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
