///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'Translation_Detail'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'Translation_Detail'.
	/// </summary>
	public class TranslationDetailDO : TranslationDetailDOBase {

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public TranslationDetailDO() : base() {
		}

		public TranslationDetailDO(int TranslationDetailID) : base() {
			this.TranslationDetailID = TranslationDetailID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
