///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'Translation_Master'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'Translation_Master'.
	/// </summary>
	public class TranslationMasterDO : TranslationMasterDOBase {

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public TranslationMasterDO() : base() {
		}

		public TranslationMasterDO(int TranslationMasterID) : base() {
			this.TranslationMasterID = TranslationMasterID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
