///////////////////////////////////////////////////////////////////////////
// Description: Data class for the 'Translation'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using FindMyFamilies.Util;

namespace FindMyFamilies.Data { 

	/// <summary>
	/// Purpose: Data Object class for the 'Translation'.
	/// </summary>
	public class TranslationDO : TranslationDOBase {

		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public TranslationDO() : base() {
		}

		public TranslationDO(int TranslationID) : base() {
			this.TranslationID = TranslationID;
		}

		// Property Declarations

		// Property Getters/Setters

	}
}
