///////////////////////////////////////////////////////////////////////////
// Description: Unit Test class for 'Member'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Reflection;

using NUnit.Framework;
using XtUnit.Extensions.Royo;
using XtUnit.Framework;

using FindMyFamilies.Data;
using FindMyFamilies.Services;

namespace FindMyFamilies.Tests {

	/// <summary>
	/// Summary description for CommandTests.
	/// </summary>
	[TestFixture]
	public class MemberTest : UnitTestBase    {

		private static readonly object logCategory = MethodBase.GetCurrentMethod().DeclaringType;

		public string[] validateFields = {
			MemberDO.LANGUAGE_ID
		};

		public MemberTest() {
			Init();
		}

		public MemberTest(string testMethod) : base(testMethod) {
			Init();
		}

		private void Init() {
			this.DataFile = "MemberData.xml";
			this.DataObjectType = "MemberDO";
		
			if (this.TestDataArray.Count < 1) {
				this.LoadData();
			}
		}
		

		public void CreateMember(ref MemberDO inputData) {
			inputData = (MemberDO) MemberServices.Instance().CreateMember(inputData);
			if (inputData.Member_ID < 1) {
				throw new TestException("Failed: Cannot create a Member. ", null);
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestCreateMembers() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					MemberDO inputData = (MemberDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					MemberDO outputData = (MemberDO) MemberServices.Instance().CreateMember(inputData);
					if (outputData.Member_ID > 0) {
						if (testData.ReadDataObject != null) {
							((MemberDO) testData.ReadDataObject).Member_ID = outputData.Member_ID;
						}
						if (testData.UpdateDataObject != null) {
							((MemberDO) testData.UpdateDataObject).Member_ID = outputData.Member_ID;
						}
						outputData = MemberServices.Instance().ReadMember(outputData);
					}
					if (outputData.Member_ID < 1) {
						throw new TestException();
					} else {
						Validate(validateFields, inputData, outputData);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot create a Member. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestUpdateMembers() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					MemberDO inputData = (MemberDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateMember(ref inputData);
					if (inputData.Member_ID > 0) {
						MemberDO memberInput = (MemberDO) testData.UpdateDataObject;
						memberInput.GetSecurityData(testData.Username, testData.Password, this.Language);
						memberInput.Member_ID = inputData.Member_ID;
						MemberServices.Instance().UpdateMember(memberInput);
						MemberDO outputData = MemberServices.Instance().ReadMember(memberInput);
						if (outputData.Member_ID > 0) {
							Validate(validateFields, memberInput, outputData);
						} else {
							throw new TestException("Failed: Cannot update a Member. ", null);
						}
					} else {
						throw new TestException();
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot update a Member. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestDeleteMembers() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					MemberDO inputData = (MemberDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateMember(ref inputData);
					if (inputData.Member_ID > 0) {
						MemberServices.Instance().DeleteMember(inputData);
						inputData = MemberServices.Instance().ReadMember(inputData);
						if (inputData.Member_ID > 0) {
							throw new TestException("Failed: Cannot delete a Member. ", null);
						}
					} else {
						throw new TestException();
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot delete a Member. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadMember() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					MemberDO inputData = (MemberDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateMember(ref inputData);
					if (inputData.Member_ID > 0) {
						MemberDO outputData = MemberServices.Instance().ReadMember(inputData);
						if (outputData.IsEmpty()) {
							throw new TestException("Failed: Cannot read a Member. ", null);
						} else {
							Validate(validateFields, inputData, outputData);
						}
					} else {
						throw new TestException("Failed: Cannot create a Member. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read a Member. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadAllMembers() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					MemberDO inputData = (MemberDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateMember(ref inputData);
					if (inputData.Member_ID > 0) {
						ICollection results = (ICollection) MemberServices.Instance().ReadMembersAll(inputData);
						if (results.Count < 1) {
							throw new TestException();
						}
					} else {
						throw new TestException("Failed: Cannot create a Member. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read all Members. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadMembersByPage() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					MemberDO inputData = (MemberDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateMember(ref inputData);
					if (inputData.Member_ID > 0) {
						inputData.Paging.PageIndex = 1;
						inputData.Paging.PageSize = 100;
						ICollection results = (ICollection) MemberServices.Instance().ReadMembersByPage(inputData);
						if (results.Count < 1) {
							throw new TestException();
						}
					} else {
						throw new TestException("Failed: Cannot create a Member. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read Members by page. ", ex);
				}
			}
		}
	}
}
