///////////////////////////////////////////////////////////////////////////
// Description: Unit Test class for 'Report'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Reflection;

using NUnit.Framework;
using XtUnit.Extensions.Royo;
using XtUnit.Framework;

using FindMyFamilies.Data;
using FindMyFamilies.Services;

namespace FindMyFamilies.Tests {

	/// <summary>
	/// Summary description for CommandTests.
	/// </summary>
	[TestFixture]
	public class ReportTest : UnitTestBase    {

		private static readonly object logCategory = MethodBase.GetCurrentMethod().DeclaringType;

		public string[] validateFields = {
			ReportDO.LANGUAGE_ID
		};

		public ReportTest() {
			Init();
		}

		public ReportTest(string testMethod) : base(testMethod) {
			Init();
		}

		private void Init() {
			this.DataFile = "ReportData.xml";
			this.DataObjectType = "ReportDO";
		
			if (this.TestDataArray.Count < 1) {
				this.LoadData();
			}
		}
		

		public void CreateReport(ref ReportDO inputData) {
			inputData = (ReportDO) PersonServices.Instance().CreateReport(inputData);
			if (inputData.Report_ID < 1) {
				throw new TestException("Failed: Cannot create a Report. ", null);
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestCreateReports() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					ReportDO inputData = (ReportDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					ReportDO outputData = (ReportDO) PersonServices.Instance().CreateReport(inputData);
					if (outputData.Report_ID > 0) {
						if (testData.ReadDataObject != null) {
							((ReportDO) testData.ReadDataObject).Report_ID = outputData.Report_ID;
						}
						if (testData.UpdateDataObject != null) {
							((ReportDO) testData.UpdateDataObject).Report_ID = outputData.Report_ID;
						}
						outputData = PersonServices.Instance().ReadReport(outputData);
					}
					if (outputData.Report_ID < 1) {
						throw new TestException();
					} else {
						Validate(validateFields, inputData, outputData);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot create a Report. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestUpdateReports() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					ReportDO inputData = (ReportDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateReport(ref inputData);
					if (inputData.Report_ID > 0) {
						ReportDO reportInput = (ReportDO) testData.UpdateDataObject;
						reportInput.GetSecurityData(testData.Username, testData.Password, this.Language);
						reportInput.Report_ID = inputData.Report_ID;
						PersonServices.Instance().UpdateReport(reportInput);
						ReportDO outputData = PersonServices.Instance().ReadReport(reportInput);
						if (outputData.Report_ID > 0) {
							Validate(validateFields, reportInput, outputData);
						} else {
							throw new TestException("Failed: Cannot update a Report. ", null);
						}
					} else {
						throw new TestException();
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot update a Report. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestDeleteReports() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					ReportDO inputData = (ReportDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateReport(ref inputData);
					if (inputData.Report_ID > 0) {
						PersonServices.Instance().DeleteReport(inputData);
						inputData = PersonServices.Instance().ReadReport(inputData);
						if (inputData.Report_ID > 0) {
							throw new TestException("Failed: Cannot delete a Report. ", null);
						}
					} else {
						throw new TestException();
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot delete a Report. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadReport() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					ReportDO inputData = (ReportDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateReport(ref inputData);
					if (inputData.Report_ID > 0) {
						ReportDO outputData = PersonServices.Instance().ReadReport(inputData);
						if (outputData.IsEmpty()) {
							throw new TestException("Failed: Cannot read a Report. ", null);
						} else {
							Validate(validateFields, inputData, outputData);
						}
					} else {
						throw new TestException("Failed: Cannot create a Report. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read a Report. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadAllReports() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					ReportDO inputData = (ReportDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateReport(ref inputData);
					if (inputData.Report_ID > 0) {
						ICollection results = (ICollection) PersonServices.Instance().ReadReportsAll(inputData);
						if (results.Count < 1) {
							throw new TestException();
						}
					} else {
						throw new TestException("Failed: Cannot create a Report. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read all Reports. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadReportsByPage() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					ReportDO inputData = (ReportDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateReport(ref inputData);
					if (inputData.Report_ID > 0) {
						inputData.Paging.PageIndex = 1;
						inputData.Paging.PageSize = 100;
						ICollection results = (ICollection) PersonServices.Instance().ReadReportsByPage(inputData);
						if (results.Count < 1) {
							throw new TestException();
						}
					} else {
						throw new TestException("Failed: Cannot create a Report. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read Reports by page. ", ex);
				}
			}
		}
	}
}
