///////////////////////////////////////////////////////////////////////////
// Description: Unit Test class for 'Translation_Detail'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Reflection;

using NUnit.Framework;
using XtUnit.Extensions.Royo;
using XtUnit.Framework;

using FindMyFamilies.Data;
using FindMyFamilies.Services;

namespace FindMyFamilies.Tests {

	/// <summary>
	/// Summary description for CommandTests.
	/// </summary>
	[TestFixture]
	public class TranslationDetailTest : UnitTestBase    {

		private static readonly object logCategory = MethodBase.GetCurrentMethod().DeclaringType;

		public string[] validateFields = {
			TranslationDetailDO.LANGUAGE_ID
		};

		public TranslationDetailTest() {
			Init();
		}

		public TranslationDetailTest(string testMethod) : base(testMethod) {
			Init();
		}

		private void Init() {
			this.DataFile = "TranslationDetailData.xml";
			this.DataObjectType = "TranslationDetailDO";
		
			if (this.TestDataArray.Count < 1) {
				this.LoadData();
			}
		}
		

		public void CreateTranslationDetail(ref TranslationDetailDO inputData) {
			inputData = (TranslationDetailDO) AdminServices.Instance().CreateTranslationDetail(inputData);
			if (inputData.Translation_Detail_ID < 1) {
				throw new TestException("Failed: Cannot create a TranslationDetail. ", null);
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestCreateTranslationDetails() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationDetailDO inputData = (TranslationDetailDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					TranslationDetailDO outputData = (TranslationDetailDO) AdminServices.Instance().CreateTranslationDetail(inputData);
					if (outputData.Translation_Detail_ID > 0) {
						if (testData.ReadDataObject != null) {
							((TranslationDetailDO) testData.ReadDataObject).Translation_Detail_ID = outputData.Translation_Detail_ID;
						}
						if (testData.UpdateDataObject != null) {
							((TranslationDetailDO) testData.UpdateDataObject).Translation_Detail_ID = outputData.Translation_Detail_ID;
						}
						outputData = AdminServices.Instance().ReadTranslationDetail(outputData);
					}
					if (outputData.Translation_Detail_ID < 1) {
						throw new TestException();
					} else {
						Validate(validateFields, inputData, outputData);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot create a TranslationDetail. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestUpdateTranslationDetails() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationDetailDO inputData = (TranslationDetailDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateTranslationDetail(ref inputData);
					if (inputData.Translation_Detail_ID > 0) {
						TranslationDetailDO translationDetailInput = (TranslationDetailDO) testData.UpdateDataObject;
						translationDetailInput.GetSecurityData(testData.Username, testData.Password, this.Language);
						translationDetailInput.Translation_Detail_ID = inputData.Translation_Detail_ID;
						AdminServices.Instance().UpdateTranslationDetail(translationDetailInput);
						TranslationDetailDO outputData = AdminServices.Instance().ReadTranslationDetail(translationDetailInput);
						if (outputData.Translation_Detail_ID > 0) {
							Validate(validateFields, translationDetailInput, outputData);
						} else {
							throw new TestException("Failed: Cannot update a TranslationDetail. ", null);
						}
					} else {
						throw new TestException();
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot update a TranslationDetail. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestDeleteTranslationDetails() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationDetailDO inputData = (TranslationDetailDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateTranslationDetail(ref inputData);
					if (inputData.Translation_Detail_ID > 0) {
						AdminServices.Instance().DeleteTranslationDetail(inputData);
						inputData = AdminServices.Instance().ReadTranslationDetail(inputData);
						if (inputData.Translation_Detail_ID > 0) {
							throw new TestException("Failed: Cannot delete a TranslationDetail. ", null);
						}
					} else {
						throw new TestException();
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot delete a TranslationDetail. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadTranslationDetail() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationDetailDO inputData = (TranslationDetailDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateTranslationDetail(ref inputData);
					if (inputData.Translation_Detail_ID > 0) {
						TranslationDetailDO outputData = AdminServices.Instance().ReadTranslationDetail(inputData);
						if (outputData.IsEmpty()) {
							throw new TestException("Failed: Cannot read a TranslationDetail. ", null);
						} else {
							Validate(validateFields, inputData, outputData);
						}
					} else {
						throw new TestException("Failed: Cannot create a TranslationDetail. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read a TranslationDetail. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadAllTranslationDetails() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationDetailDO inputData = (TranslationDetailDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateTranslationDetail(ref inputData);
					if (inputData.Translation_Detail_ID > 0) {
						ICollection results = (ICollection) AdminServices.Instance().ReadTranslationDetailsAll(inputData);
						if (results.Count < 1) {
							throw new TestException();
						}
					} else {
						throw new TestException("Failed: Cannot create a TranslationDetail. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read all TranslationDetails. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadTranslationDetailsByPage() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationDetailDO inputData = (TranslationDetailDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateTranslationDetail(ref inputData);
					if (inputData.Translation_Detail_ID > 0) {
						inputData.Paging.PageIndex = 1;
						inputData.Paging.PageSize = 100;
						ICollection results = (ICollection) AdminServices.Instance().ReadTranslationDetailsByPage(inputData);
						if (results.Count < 1) {
							throw new TestException();
						}
					} else {
						throw new TestException("Failed: Cannot create a TranslationDetail. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read TranslationDetails by page. ", ex);
				}
			}
		}
	}
}
