///////////////////////////////////////////////////////////////////////////
// Description: Unit Test class for 'Translation_Master'
// Generated by FindMyFamilies Generator
///////////////////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Reflection;

using NUnit.Framework;
using XtUnit.Extensions.Royo;
using XtUnit.Framework;

using FindMyFamilies.Data;
using FindMyFamilies.Services;

namespace FindMyFamilies.Tests {

	/// <summary>
	/// Summary description for CommandTests.
	/// </summary>
	[TestFixture]
	public class TranslationMasterTest : UnitTestBase    {

		private static readonly object logCategory = MethodBase.GetCurrentMethod().DeclaringType;

		public string[] validateFields = {
			TranslationMasterDO.LANGUAGE_ID
		};

		public TranslationMasterTest() {
			Init();
		}

		public TranslationMasterTest(string testMethod) : base(testMethod) {
			Init();
		}

		private void Init() {
			this.DataFile = "TranslationMasterData.xml";
			this.DataObjectType = "TranslationMasterDO";
		
			if (this.TestDataArray.Count < 1) {
				this.LoadData();
			}
		}
		

		public void CreateTranslationMaster(ref TranslationMasterDO inputData) {
			inputData = (TranslationMasterDO) AdminServices.Instance().CreateTranslationMaster(inputData);
			if (inputData.Translation_Master_ID < 1) {
				throw new TestException("Failed: Cannot create a TranslationMaster. ", null);
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestCreateTranslationMasters() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationMasterDO inputData = (TranslationMasterDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					TranslationMasterDO outputData = (TranslationMasterDO) AdminServices.Instance().CreateTranslationMaster(inputData);
					if (outputData.Translation_Master_ID > 0) {
						if (testData.ReadDataObject != null) {
							((TranslationMasterDO) testData.ReadDataObject).Translation_Master_ID = outputData.Translation_Master_ID;
						}
						if (testData.UpdateDataObject != null) {
							((TranslationMasterDO) testData.UpdateDataObject).Translation_Master_ID = outputData.Translation_Master_ID;
						}
						outputData = AdminServices.Instance().ReadTranslationMaster(outputData);
					}
					if (outputData.Translation_Master_ID < 1) {
						throw new TestException();
					} else {
						Validate(validateFields, inputData, outputData);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot create a TranslationMaster. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestUpdateTranslationMasters() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationMasterDO inputData = (TranslationMasterDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateTranslationMaster(ref inputData);
					if (inputData.Translation_Master_ID > 0) {
						TranslationMasterDO translationMasterInput = (TranslationMasterDO) testData.UpdateDataObject;
						translationMasterInput.GetSecurityData(testData.Username, testData.Password, this.Language);
						translationMasterInput.Translation_Master_ID = inputData.Translation_Master_ID;
						AdminServices.Instance().UpdateTranslationMaster(translationMasterInput);
						TranslationMasterDO outputData = AdminServices.Instance().ReadTranslationMaster(translationMasterInput);
						if (outputData.Translation_Master_ID > 0) {
							Validate(validateFields, translationMasterInput, outputData);
						} else {
							throw new TestException("Failed: Cannot update a TranslationMaster. ", null);
						}
					} else {
						throw new TestException();
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot update a TranslationMaster. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestDeleteTranslationMasters() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationMasterDO inputData = (TranslationMasterDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateTranslationMaster(ref inputData);
					if (inputData.Translation_Master_ID > 0) {
						AdminServices.Instance().DeleteTranslationMaster(inputData);
						inputData = AdminServices.Instance().ReadTranslationMaster(inputData);
						if (inputData.Translation_Master_ID > 0) {
							throw new TestException("Failed: Cannot delete a TranslationMaster. ", null);
						}
					} else {
						throw new TestException();
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot delete a TranslationMaster. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadTranslationMaster() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationMasterDO inputData = (TranslationMasterDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateTranslationMaster(ref inputData);
					if (inputData.Translation_Master_ID > 0) {
						TranslationMasterDO outputData = AdminServices.Instance().ReadTranslationMaster(inputData);
						if (outputData.IsEmpty()) {
							throw new TestException("Failed: Cannot read a TranslationMaster. ", null);
						} else {
							Validate(validateFields, inputData, outputData);
						}
					} else {
						throw new TestException("Failed: Cannot create a TranslationMaster. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read a TranslationMaster. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadAllTranslationMasters() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationMasterDO inputData = (TranslationMasterDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateTranslationMaster(ref inputData);
					if (inputData.Translation_Master_ID > 0) {
						ICollection results = (ICollection) AdminServices.Instance().ReadTranslationMastersAll(inputData);
						if (results.Count < 1) {
							throw new TestException();
						}
					} else {
						throw new TestException("Failed: Cannot create a TranslationMaster. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read all TranslationMasters. ", ex);
				}
			}
		}
		
		[Test, CustomRollBack, CustomTracing]
		public void TestReadTranslationMastersByPage() {
			for (this.Row = 1; this.Row < this.TestDataArray.Count; this.Row++) {
				try {
					TestData testData = (TestData) this.TestDataArray[this.Row];
					TranslationMasterDO inputData = (TranslationMasterDO) testData.ReadDataObject;
					inputData.GetSecurityData(testData.Username, testData.Password, this.Language);
					CreateTranslationMaster(ref inputData);
					if (inputData.Translation_Master_ID > 0) {
						inputData.Paging.PageIndex = 1;
						inputData.Paging.PageSize = 100;
						ICollection results = (ICollection) AdminServices.Instance().ReadTranslationMastersByPage(inputData);
						if (results.Count < 1) {
							throw new TestException();
						}
					} else {
						throw new TestException("Failed: Cannot create a TranslationMaster. ", null);
					}
				} catch (Exception ex) {
					throw new TestException("Failed: Cannot read TranslationMasters by page. ", ex);
				}
			}
		}
	}
}
